// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type SeckillActivity struct {
	ID           uint64
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	SkuID        uint64
	Price        float64
	SeckillPrice float64
	Stock        int64
	StartTime    time.Time
	EndTime      time.Time
}

type SeckillOrder struct {
	ID         uint64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uint64
	ActivityID uint64
	SkuID      uint64
	Price      float64
	Status     int64
}
