// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const decrStock = `-- name: DecrStock :execrows
UPDATE seckill_activities
SET stock = stock - 1
WHERE sku_id = ? AND stock > 0
`

func (q *Queries) DecrStock(ctx context.Context, skuID uint64) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrStock, skuID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO seckill_orders (user_id, activity_id, sku_id, price)
VALUES (?, ?, ?, ?)
`

type InsertOrderParams struct {
	UserID     uint64
	ActivityID uint64
	SkuID      uint64
	Price      float64
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.ExecContext(ctx, insertOrder,
		arg.UserID,
		arg.ActivityID,
		arg.SkuID,
		arg.Price,
	)
	return err
}
